### ISSUE TITLE
Not all ranges stay editable

### ISSUE THREAD

**Issue by Lyannic** [Pranomvignesh/constrained-editor-plugin#7]
Thank you for publishing this plugin!
I just played around a bit in your playground. During that, I noticed that when I do some changes to the second range (`// Enter the content for the function here`), I am not able to edit the second range (`utils`) anymore. 
Is this some special case and actually meant to be or is it a bug? In the first case, it would be nice to have some information in the documentation.

**Comment by Pranomvignesh** [comment]
Hi @Lyannic , I require more information about the issue

For me, Playground works as indented, So it would be nice if you can share a screen recording demo of the issue so that I can clarify your issue.

General Information about the Playground's Range Configuration
- 1st Range - utilName 
    - doesn't have allowMultiline as `True` so New Line Characters won't work
    - validation callback returns false for spaces and special characters, so that won't work
 - 2nd Range - funcDefinition
    - has allowMultiline as `True`, so New Line Characters will work
    
All the above mentioned configuration are explained in detail here - [ Restrictions Object ](https://constrained-editor-plugin.vercel.app/docs/Usage/restrictions-object)

>it would be nice to have some information in the documentation.

Quick Start Code is actually rendered in the playground [QuickStart](https://constrained-editor-plugin.vercel.app/docs/intro#quick-start) , So I request you to go through it again

**Comment by Lyannic** [comment]
I created a little GIF for you. Since you can't actually see, when I am trying to type: after I write the "f"s into the second range, I am trying to edit the first range again which doesn't work. The second range however stays editable.

![Peek 2021-12-09 16-28](https://user-images.githubusercontent.com/17884358/145425688-69d8fb97-c26c-4c27-a94d-2e3f6f07f0c5.gif)

**Comment by Pranomvignesh** [comment]
Array Sort Methods behaves differently on different browsers [FreeCodeCamp Forum Link](https://forum.freecodecamp.org/t/the-sort-method-behaves-different-on-different-browsers/237221)

This was the root cause of the issue. It is now fixed and a new version (constrained-editor-plugin@1.0.6) is now released

**Comment by Lyannic** [comment]
Nice, that was fast. I can confirm that it now works in Firefox in the playground.
