### ISSUE TITLE
Indicate restricted areas for the end user

### ISSUE THREAD

**Issue by Lyannic** [Pranomvignesh/constrained-editor-plugin#9]
It is stated in the README that this plugin can be used in coding tutorial applications. I think that for this use case it is almost necessary to indicate to the user in a nice way, which areas he can actually edit. In issue #4 it got mentioned that the highlighting is a dev feature. 
In my opinion, it would be nice if the end user could see the restricted areas in like a pale color or maybe a red. Another option could be, to give the user of the library the possibility, to easily adapt the style of the restricted and unristricted areas. Or is that even easily possible already?
Is a feature like this already planned?

**Comment by Pranomvignesh** [comment]
@Lyannic Thanks for the suggestion

> In my opinion, it would be nice if the end user could see the restricted areas in like a pale color or maybe a red

I cannot statically declare the UI of the restricted areas and declare that as a production ready method.

I have a practical difficulty in exposing and maintaining that as an method from this plugin.
If the [toggleHighlightOfEditableAreas](https://constrained-editor-plugin.vercel.app/docs/AvailableAPI/monaco-editor-model-api#togglehighlightofeditableareas) has to function to the expected level of customization, my argument structure should be same as [deltaDecorations](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IStandaloneCodeEditor.html#deltaDecorations) method of monaco editor. The only thing which my method can add instead of expecting it from you is the `range of the editable area`.

This feels like just wrapping a monaco editor method inside this plugin's method **without adding any value to it.**

### Workaround

>to give the user of the library the possibility, to easily adapt the style of the restricted and unristricted areas.

>Or is that even easily possible already?

Like you said, There is a workaround for you
- Use the [getCurrentEditableRanges](https://constrained-editor-plugin.vercel.app/docs/AvailableAPI/monaco-editor-model-api#getcurrenteditableranges) to get the range at any point of time
- Use the [deltaDecorations](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IStandaloneCodeEditor.html#deltaDecorations) method of monaco editor to add the decorations by yourself.

So the method **toggleHighlightOfEditableAreas is and it will remain as an method to be used in the dev environment.** Please use the workaround to highlight the content for the end users.

Hope this helps you

**Comment by Lyannic** [comment]
Thank you very much for you fast and detailed answer. I completely overlooked the `getCurrentEditableRanges` function. That solves the problem :+1:
